[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2"
name = "Trainworks_Reloaded"
versionNumber = "0.1.1"
description = "A Data Loader and Injection Engine for Monster Train 2"
websiteUrl = "https://github.com/Monster-Train-2-Modding-Group/Trainworks-Reloaded"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./DESCRIPTION.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


