name: Release Build

on:
  push:
    tags:
      - "*"

permissions:
    packages: write
    contents: write
    
env:
  mod_namespace: 'MT2'
  mod_name: 'Trainworks_Reloaded'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Compatible with netstandard2.1

      - name: Install Thunderstore
        run: |
          dotnet tool install --global tcli

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup NuGet Credentials
        run: |
          dotnet nuget update source monster-train-packages -u USERNAME -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution with Versioning
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore /p:Version=${VERSION}

      - name: Build Plugin
        run: dotnet publish TrainworksReloaded.Plugin/TrainworksReloaded.Plugin.csproj --configuration Release --output ./plugin_build /p:Version=${VERSION}

      - name: Build Thunderstore Package
        run: |
          tcli build

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-bundle
          path: ${{ env.mod_namespace }}-${{ env.mod_name }}-${{ github.ref_name }}.zip
          
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.mod_namespace }}-${{ env.mod_name }}-${{ github.ref_name }}.zip
          prerelease: true
          generate_release_notes: true

      - name: Publish to Thunderstore
        run: tcli publish --file "${{ env.mod_namespace }}-${{ env.mod_name }}-${{ github.ref_name }}.zip" --token ${{ secrets.TCLI_AUTH_TOKEN }}